package com.smart_delivery_platform.order_service.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Schema(description = "Order details returned by the order service.")
public class OrderDTO {
    @Schema(description = "Order ID generated by the order service.", example = "ORD-1A2B3C4D")
    private String orderId;

    @Schema(description = "Customer that placed the order.", example = "CUST-1001")
    private String customerId;

    @Schema(description = "Restaurant fulfilling the order.", example = "REST-2001")
    private String restaurantId;

    @Schema(description = "Total order amount.", example = "549.50")
    private Double amount;

    @Schema(description = "Current order status.", example = "PAYMENT_PENDING")
    private String status;

    @Schema(description = "Order creation timestamp.", example = "2026-06-28T10:15:30")
    private LocalDateTime createdAt;

    @Schema(description = "Last update timestamp.", example = "2026-06-28T10:20:30")
    private LocalDateTime updatedAt;
}
