package com.smart_delivery_platform.payment_service.controller;

import com.smart_delivery_platform.payment_service.service.IPaymentService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/payments/")
@Tag(name = "Payments", description = "Payment and refund operations.")
public class PaymentController {

    private final IPaymentService paymentService;

    public PaymentController(IPaymentService paymentService) {
        this.paymentService = paymentService;
    }

    @PostMapping("/{orderId}/retry-refund")
    @Operation(
            summary = "Retry refund for an order",
            description = "Starts a refund retry flow for the given order.",
            responses = @ApiResponse(
                    responseCode = "200",
                    description = "Refund retry result",
                    content = @Content(
                            mediaType = "text/plain",
                            examples = @ExampleObject(value = "Refund Successfully")
                    )
            )
    )
    public String refundInitiation(
            @Parameter(description = "Order ID generated by the order service", example = "ORD-1A2B3C4D")
            @PathVariable String orderId){
        paymentService.refundInitiation(orderId);
        return "Refund Successfully";
    }
}
