server:
  port: 8085

spring:
  application:
    name: ORDER-SERVICE

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.smart_delivery_platform.order_service.dto.DeliveryAssignedEvent
        spring.json.use.type.headers: false


    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_delivery_order_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

resilience4j:
  circuitbreaker:
    instances:
      restaurantService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 3
        sliding-window-size: 5
        wait-duration-in-open-state: 10s