package com.smart_delivery_platform.order_service.controller;

import com.smart_delivery_platform.order_service.dto.CreateOrderRequest;
import com.smart_delivery_platform.order_service.dto.OrderCreatedEvent;
import com.smart_delivery_platform.order_service.dto.OrderDTO;
import com.smart_delivery_platform.order_service.service.IOrderService;
import com.smart_delivery_platform.order_service.service.OrderProducer;
import com.smart_delivery_platform.order_service.service.RestaurantAvailabilityService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;
import java.util.UUID;

import static com.smart_delivery_platform.order_service.utility.RequestToVO.requestToEvent;

@RestController
@RequestMapping("/api/orders")
@RequiredArgsConstructor
@Tag(name = "Orders", description = "Create orders, fetch order details, and retry failed payments.")
public class OrderController {

    private final OrderProducer orderProducer;
    private final IOrderService orderService;
    private final RestaurantAvailabilityService restaurantAvailabilityService;


    @GetMapping("/test")
    @Operation(
            summary = "Check order service status",
            responses = @ApiResponse(responseCode = "200", description = "Order service is running")
    )
    public String test() {
        return "Order Service is running";
    }

    @PostMapping
    @Operation(
            summary = "Create a new order",
            description = "Creates an order, checks restaurant availability, stores the order, and publishes an order-created event when the restaurant service is available.",
            responses = {
                    @ApiResponse(
                            responseCode = "200",
                            description = "Order creation request processed",
                            content = @Content(
                                    mediaType = "text/plain",
                                    examples = {
                                            @ExampleObject(name = "Success", value = "Order Created Successfully"),
                                            @ExampleObject(name = "Restaurant service down", value = "restaurant service is down")
                                    }
                            )
                    )
            }
    )
    public String createOrder(@RequestBody CreateOrderRequest orderRequest) {
        String orderId = generateRandomOrderId();
        String response = restaurantAvailabilityService.checkRestaurant(orderRequest.getRestaurantId());
        if(response.equals("RESTAURANT_SERVICE_DOWN")){
            orderService.saveOrder(orderRequest,orderId,null);
            return "restaurant service is down";
        }else{
            OrderCreatedEvent orderCreatedEvent = requestToEvent(orderRequest);
            orderCreatedEvent.setOrderId(orderId);
            orderService.saveOrder(orderRequest,orderId,null);
            orderProducer.publishOrderEvent(orderCreatedEvent);
        }

        return "Order Created Successfully";
    }

    public static String generateRandomOrderId() {
        return "ORD-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();
    }

    @GetMapping("/{orderId}")
    @Operation(
            summary = "Get order by ID",
            responses = @ApiResponse(
                    responseCode = "200",
                    description = "Order details",
                    content = @Content(schema = @Schema(implementation = OrderDTO.class))
            )
    )
    public OrderDTO getOrder(
            @Parameter(description = "Order ID generated by the order service", example = "ORD-1A2B3C4D")
            @PathVariable String orderId) {
        return  orderService.getOrder(orderId);
    }

    @PostMapping("/{orderId}/retry-payment")
    @Operation(
            summary = "Retry payment for an order",
            description = "Retries payment only for orders in PAYMENT-FAILED, CREATED, or PAYMENT_PENDING status.",
            responses = @ApiResponse(
                    responseCode = "200",
                    description = "Payment retry decision",
                    content = @Content(
                            mediaType = "text/plain",
                            examples = {
                                    @ExampleObject(name = "Retry initiated", value = "Payment retry initiated"),
                                    @ExampleObject(name = "Retry not allowed", value = "Payment retry not allowed")
                            }
                    )
            )
    )
    public String retryPayment(
            @Parameter(description = "Order ID generated by the order service", example = "ORD-1A2B3C4D")
            @PathVariable String orderId) {
        OrderDTO order = orderService.getOrder(orderId);
        if(order.getStatus().equals("PAYMENT-FAILED") || order.getStatus().equals("CREATED")
        || order.getStatus().equals("PAYMENT_PENDING")){
            orderService.updateOrderStatus(orderId,"PAYMENT_PENDING");
            OrderCreatedEvent orderCreatedEvent = OrderCreatedEvent.builder()
                    .amount(order.getAmount())
                    .restaurantId(order.getRestaurantId())
                    .orderId(orderId).build();
            orderProducer.publishOrderEvent(orderCreatedEvent);
            return "Payment retry initiated";

        }
        return "Payment retry not allowed";
    }


}
